version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    groups:
      playwright:
        patterns:
          - "playwright"
          - "@playwright/*"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
