name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '14'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint --max-warnings 0

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '14'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: test
        run: yarn test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: '14'
        cache: yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build
